#pragma once

#define PRECHARGE_PIN_SDC_EFUSE_FAULT   1
#define PRECHARGE_PIN_RTDS_AIRS_CLOSED  5
#define PRECHARGE_PIN_LED_D7            18
#define PRECHARGE_PIN_LED_D8            17
#define PRECHARGE_PIN_AIR_POS_CTRL      2
#define PRECHARGE_PIN_AIR_NEG_CTRL      3
#define PRECHARGE_PIN_PRECH_RELAY_CTRL  4
#define PRECHARGE_ANALOG_PIN_ISOAMP_IN  6
#define PRECHARGE_PIN_EXTRA_SCREW_TERM  7

#define PRECHARGE_ADC_OFFSET_MV           (1415U)
#define PRECHARGE_ADC_GAIN_ISOAMP_MV_TO_V (0.3673769f)

// do what's right | made with <3 at Cooper Union
